# Generated by Django 5.1 on 2025-07-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
