# Generated by Django 5.2.4 on 2025-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='accounts_app/images/default_profile_pic.png', upload_to='', verbose_name='Profile photo'),
        ),
    ]
