# Generated by Django 5.2.4 on 2025-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='accounts_app/profile_photo/default_profile_pic.png', upload_to='accounts_app/profile_photo/', verbose_name='Profile photo'),
        ),
    ]
