# Generated by Django 5.2.4 on 2025-09-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product name')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('manufacturer', models.CharField(blank=True, max_length=120, null=True, verbose_name='Product manufacturer')),
                ('image', models.ImageField(default='shop_app/products_photo/default_product_pic.png', upload_to='shop_app/products_photo/', verbose_name='Product image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_app.category', verbose_name='Product category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
