# Generated by Django 5.2.4 on 2025-09-04 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Discount price'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Product is active'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(default=0, verbose_name='Product quantity in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Q', 'шт'), ('W', 'кг')], default='Q', max_length=1, verbose_name='Product unit type'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_in_stock',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Product weight in stock'),
        ),
    ]
