# Generated by Django 5.2.4 on 2025-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_tag_remove_category_description_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tags', to='shop_app.category', verbose_name='Categories'),
        ),
    ]
