# Generated by Django 5.2.4 on 2025-09-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_tag_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='categories',
        ),
    ]
