# Generated by Django 5.2.4 on 2025-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_remove_tag_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level_view',
            field=models.IntegerField(default=1, verbose_name='Category level view'),
        ),
    ]
